name: Build ShittyOS # does GitHub care about swearing?

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install NASM
        run: sudo apt-get update && sudo apt-get install -y NASM
      
      - name: Assemble ShittyOS
        run: nasm -f bin shittyos.asm -o shittyos.img

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: "ShittyOS v${{ github.run_number }}"
          body: "Automatically built ShittyOS img, if you dare use this on hardware/in a VM. Prepare to be underwhelmed."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload .img
        uses: softprops/action-gh-release@v1
        with:
          files: shittyos.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}