name: Build ShittyOS # does GitHub care about swearing?

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install NASM
        run: sudo apt-get update && sudo apt-get install -y nasm
      
      - name: Assemble ShittyOS
        run: nasm -f bin theentirething.asm -o shittyos.img

      - name: Release
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: attempt-1
        with:
          name: "ShittyOS v${{ github.run_number }}"
          tag_name: nightly
          body_path: changes.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            shittyos.img